account/urls.py
from django.urls import path
from . import views

app_name = 'account'

# admin.site.login = custom.site.login

urlpatterns = [
    path('', views.home, name='home'),
    path('index/<workplace>', views.index, name='index'),
    path('users/<workplace>', views.manage_users, name='manage_users'),
    path('index/', views.single_user_index, name='single-index'),
    path('account/sent/email', views.sent_mail, name='sent-email'),
    path('account/invite/users/<workplace>', views.invite_users, name='invite-users'),
    path('account/<slug:slug>/<workplace>', views.user_detail, name='user-detail'),
    path('account/signup', views.signup, name='signup'),
    path('account/signup/<workplace>/<email>', views.signup_workplace, name='signup-workplace'),
    path('account/login', views.login_view, name='login'),
    path('account/logout', views.logout_view, name='logout'),
    path('account/activate/view/<email>', views.activate_email, name='activate-email'),
    path('account/activate/test/<email>', views.activate, name='activate'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/mdb.min.js' %}"></script>
     <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
      background: #78909c !important;
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
      background: #78909c !important;
    }

  </style>
</head>

  {% include "navbar.html" %}



<body class="cyan-skin">
  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}

          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
    {% endif %}
  </div>


  <!-- Content here -->
  <main>
        {% block content  %}
        {% endblock content %}
  </main>



  {% block extra_body %}
    {% endblock %}

   {% comment %} {% include "footer.html" %}
  {% include "scripts.html" %}
    {% block extra_scripts %}
    {% endblock extra_scripts %} {% endcomment %}
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/base_email.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/mdb.min.js' %}"></script>
     <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
      background: #78909c !important;
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
      background: #78909c !important;
    }

  </style>
</head>



<body class="cyan-skin">
  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}

          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
    {% endif %}
  </div>


  <!-- Content here -->
  <main>
        {% block content  %}
        {% endblock content %}
  </main>



  {% block extra_body %}
    {% endblock %}

   {% comment %} {% include "footer.html" %}
  {% include "scripts.html" %}
    {% block extra_scripts %}
    {% endblock extra_scripts %} {% endcomment %}
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/home.html
  <!--/.Carousel Wrapper-->
{% extends "base.html" %}

{% block content %}
  <!--Main layout-->
  
    <div class="container">

    <div class="row mx-auto">
        <div class="col-md-12 mb-4 text-center wow fadeIn">
          <h3 class="display-3 font-weight-bold mb-0 pt-md-5 pt-5">Project Managemnet</h3>
          <hr class="hr-dark my-4 w-75">
          <h4 class="subtext-header mt-2 mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing
            elit deleniti consequuntur nihil.A test</h4>
        <div class="d-flex justify-content-center">
          <div class="p-2"> <a type="button" class="btn btn-primary" href="{% url 'account:signup' %}">Signup</a></div>
          <div class="p-2"><a type="button" class="btn btn-default" href="{% url 'account:login' %}">login</a></div>
          {% comment %} <div class="p-2">Flex item 3</div> {% endcomment %}
        </div>
         
          
        </div>
        {% comment %} <div class="col">
          2 of 2
        </div> {% endcomment %}
      </div>

    </div>

  <!--Main layout-->


{% endblock %}

templates/navbar.html
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark primary-color scrolling-navbar">
    {% comment %} <div class="container"> {% endcomment %}

      <!-- Brand -->
      <a class="navbar-brand waves-effect" target="_blank">
        <strong class="blue-text">WorkPlace</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <!--<li class="nav-item active">
            <a class="nav-link waves-effect">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>-->
          <!-- <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">About MDB</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
              target="_blank">Free download</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/" target="_blank">Free
              tutorials</a>
          </li> -->
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}

           <li class="nav-item">
           
            <a class="nav-link waves-effect" href="{% url 'account:logout' %}">
              <span class="clearfix d-none d-sm-inline-block">Hello {{ request.user.full_name }} | Logout</span>
            </a>
           
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" >
              <span class="clearfix d-none d-sm-inline-block" href="{% url 'account:login' %}"> Login</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect">
              <span class="clearfix d-none d-sm-inline-block" href="{% url 'account:signup' %}"> Signup</span>
            </a>
          </li>
         {% endif %}
          <!--<li class="nav-item">
            <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="nav-link border border-light rounded waves-effect"
              target="_blank">
              <i class="fab fa-github mr-2"></i>MDB GitHub
            </a>
          </li>-->
        </ul>

      </div>

    {% comment %} </div> {% endcomment %}
  </nav>
  <!-- Navbar -->