account/urls.py
from django.urls import path
from . import views

app_name = 'account'

# admin.site.login = custom.site.login

urlpatterns = [
    path('', views.home, name='home'),
    path('index/<workplace>', views.index, name='index'),
    path('users/<workplace>', views.manage_users, name='manage_users'),
    path('index/', views.single_user_index, name='single-index'),
    path('account/sent/email', views.sent_mail, name='sent-email'),
    path('account/invite/users/<workplace>', views.invite_users, name='invite-users'),
    path('account/<slug:slug>/<workplace>', views.user_detail, name='user-detail'),
    path('account/signup', views.signup, name='signup'),
    path('account/signup/<workplace>/<email>', views.signup_workplace, name='signup-workplace'),
    path('account/login', views.login_view, name='login'),
    path('account/logout', views.logout_view, name='logout'),
    path('account/activate/view/<email>', views.activate_email, name='activate-email'),
    path('account/activate/test/<email>', views.activate, name='activate'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

# admin.site.login = custom.site.login

urlpatterns = [
    path('<workplace>', views.index, name='index'),
    path('<workplace_id>/<slug:slug>', views.project_detail, name="project-detail"),
    path('<workplace_id>/<slug:proj_slug>/<int:pk>/<str:task_name>', views.task_detail, name="task-detail"),
    # path('<workplace_id>/<slug:proj_slug>/<int:pk>/<str:task_name>', views.task_delete, name="task-delete"),
]

projects/models.py
from django.db import models
from account.models import AccountUser, WorkPlace
from django.urls import reverse
from django.template.defaultfilters import slugify

status = (
    ('ass', 'Assigned'),
    ('prog', 'In Progress'),
    ('comp', 'Completed'),
    ('test', 'Testing'),
    ('rev', 'Review'),
    ('appr', 'Approved'),
    ('rel', 'Released')
)

# Create your models here.

class Project(models.Model):
    workplace_id = models.ForeignKey(WorkPlace, on_delete=models.CASCADE)
    project_manager = models.ForeignKey(AccountUser, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255)
    date_created = models.DateTimeField(verbose_name='date created', auto_now_add=True)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.name

    def assigned(self):
        var = Status.objects.get(status='ass')
        return self.tasks_set.filter(status_id_id=var)

    def progress(self):
        var = Status.objects.get(status='prog')
        return self.tasks_set.filter(status_id_id=var)

    def completed(self):
        var = Status.objects.get(status='comp')
        return self.tasks_set.filter(status_id_id=var)

    def testing(self):
        var = Status.objects.get(status='test')
        return self.tasks_set.filter(status_id_id=var)

    def review(self):
        var = Status.objects.get(status='rev')
        return self.tasks_set.filter(status_id_id=var)

    def approved(self):
        var = Status.objects.get(status='appr')
        return self.tasks_set.filter(status_id_id=var)

    def released(self):
        var = Status.objects.get(status='rel')
        return self.tasks_set.filter(status_id_id=var)

    def get_absolute_url(self):
        return reverse('projects:project-detail', kwargs={'workplace_id': self.workplace_id, 'slug': self.slug})

    def save(self, *args, **kwargs): # new
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Status(models.Model):
    status = models.CharField(max_length=15, choices=status, null=True, blank=True)

    def __str__(self):
        return self.status


class Tasks(models.Model):
    project_id = models.ForeignKey(Project, on_delete=models.CASCADE)
    user_id = models.ForeignKey(AccountUser, on_delete=models.SET_NULL, null=True)
    status_id = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=256)
    date_created = models.DateTimeField(verbose_name='date created', auto_now_add=True)

    def __str__(self):
        return self.name


class Logs(models.Model):
    task_id = models.ForeignKey(Tasks, on_delete=models.CASCADE)
    messages = models.TextField()
    date_created = models.DateTimeField(verbose_name='date created', auto_now_add=True)

    def __str__(self):
        return self.messages

projects/forms.py
from django import forms
from .models import Project, Tasks

class TasksForm(forms.ModelForm):
    class Meta:
        model = Tasks
        fields = ('name', 'status_id')

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Tasks, Status, Logs
from account.models import WorkPlace, AccountUser
from .forms import TasksForm
from django.contrib import messages
from django.db import transaction
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def index(request, workplace):
    workplace_id = get_object_or_404(WorkPlace, name=workplace)
    users = AccountUser.objects.filter(workplace_id=workplace_id, role='PR')
    projects = Project.objects.filter(workplace_id=workplace_id)
    context = {'projects': projects,
               'users': users
        }

    if request.method == 'POST':
        project_name = request.POST.get('project_name')
        project_manager = request.POST.get('project_manager')
        print(project_manager)
        print("here")
        # manager_id = AccountUser.objects.get(id=project_manager)
        # print(manager_id)
        if project_name and project_manager:
            Project.objects.create(workplace_id=workplace_id, 
                                name=project_name,
                                project_manager_id=project_manager)
            return redirect('projects:index', workplace=workplace)
        else:
            messages.error(request, "Fill in the project name and project manager")
            return redirect('projects:index', workplace=workplace)

        # return redirect('projects:index', workplace=workplace)
    return render(request, 'project/project_index.html', context)

@login_required
def project_detail(request, workplace_id, slug):
    workplace_id = get_object_or_404(WorkPlace, name=workplace_id)
    project_id = get_object_or_404(Project, workplace_id=workplace_id, slug=slug)
    projects = Project.objects.filter(workplace_id=workplace_id, slug=slug)
    tasks = Tasks.objects.filter(project_id=project_id)
    status_id = get_object_or_404(Status, status='ass')
    user_id = get_object_or_404(AccountUser, pk=request.user.pk)

    if request.method == 'POST':
        if request.POST.get('task'):
            task_name = request.POST.get('task')
            with transaction.atomic():
                task_obj = Tasks.objects.create(
                    project_id=project_id,
                    user_id=user_id,
                    status_id=status_id,
                    name=task_name
                )
                mssg = "Task created on {0}\n assigned to {1}"
                date_field_to_date = task_obj.date_created.date()
                get_date = date_field_to_date.strftime("%Y-%m-%d")
                get_mssg = mssg.format(get_date, task_obj.user_id.full_name())
                Logs.objects.create(task_id=task_obj, messages=get_mssg)
                messages.success(request, "Your task has been created!")
                return redirect('projects:project-detail', workplace_id=workplace_id, slug=slug)

    context = {
        'tasks': tasks,
        'projects': projects
    }
    return render(request, 'project/project_detail.html', context)

@login_required
def task_detail(request, workplace_id, proj_slug, pk, task_name):
    # status = 
    if request.user.is_authenticated:
        workplace_id = get_object_or_404(WorkPlace, name=workplace_id)
        users = AccountUser.objects.filter(workplace_id=workplace_id)
        proj_detail = get_object_or_404(Project, workplace_id=workplace_id, slug=proj_slug)
        task_detail = get_object_or_404(Tasks, project_id=proj_detail,
                                        pk=pk, name=task_name)
        logs = Logs.objects.filter(task_id=task_detail).order_by('-date_created')
        curr_user_group = request.user.role
        mssg = ""

        if request.method == 'POST':
            if request.POST.get('task_name') or request.POST.get('assign_to') or \
               request.POST.get('status'):
                # status_obj = get_object_or_404(Status, status=request.POST.get('status'))
                # user_obj = get_object_or_404(AccountUser, pk=request.POST.get('pk'))
                    with transaction.atomic():
                        if request.POST.get('task_name'):
                            task_detail.name = request.POST.get('task_name')
                            mssg = "You Have changed this task name"
                        if request.POST.get('assign_to'):
                            user_obj = get_object_or_404(AccountUser, pk=request.POST.get('assign_to'))
                            task_detail.user_id = user_obj
                            mssg = "You have assigned this task to \n ----> {}".format(task_detail.user_id.full_name())
                        if request.POST.get('status'):
                            print(request.POST.get('status'))
                            status_obj = get_object_or_404(Status, status=request.POST.get('status'))
                            print(status_obj)
                            task_detail.status_id = status_obj
                            if task_detail.status_id.status == 'ass':
                                mssg = "Assigned"
                            elif task_detail.status_id.status == 'prog':
                                mssg = "in Progress"
                            elif task_detail.status_id.status == 'comp':
                                mssg = "Completed"
                            elif task_detail.status_id.status == 'test':
                                mssg = "in Testing"
                            elif task_detail.status_id.status == 'rev':
                                mssg = "in Review"
                            elif task_detail.status_id.status == 'appr':
                                mssg = "Approved"
                            elif task_detail.status_id.status == 'rel':
                                mssg = "Released Congratulations!"
                        get_mssg = "This task is now \n   -------> {}".format(mssg)
                        Logs.objects.create(task_id=task_detail, messages=get_mssg)
                        task_detail.save()
                        messages.success(request, "Your task has been Updated!")
                        return redirect('projects:task-detail',
                                        workplace_id=workplace_id.name, 
                                        proj_slug=proj_slug,
                                        pk=pk, task_name=task_name)

            if request.POST.get('message'):
                message = request.POST.get('message')
                Logs.objects.create(task_id=task_detail, messages=message)
                return redirect('projects:task-detail',
                                        workplace_id=workplace_id.name, 
                                        proj_slug=proj_slug,
                                        pk=pk, task_name=task_name)
            
            if request.POST.get('delete-task') == 'delete':
                task_detail.delete()
                messages.success(request, "Your task has been Deleted!")
                return redirect('projects:project-detail', workplace_id=workplace_id, slug=proj_slug)
    else:
        return redirect('account:home')

    
    context = {
        'task_detail': task_detail,
        'users': users,
        'logs': logs
    }
    return render(request, 'project/task_detail.html', context)

    

templates/project/index.html
{% extends "base.html" %}

{% block content %}
  <!--Main layout-->
  
    {% comment %} <div class="container"> {% endcomment %}
{% if request.user.is_active == True %}
    <div class="row mx-auto">
       
             {% comment %} <div class="col-2">
                <div id="list-example" class="list-group">
                  <a class="list-group-item list-group-item-action active" href="#list-item-1">Item 1</a>
                  <a class="list-group-item list-group-item-action" href="#list-item-2">Item2</a>
                  <a class="list-group-item list-group-item-action" href="#list-item-3">Item 3</a>
                  <a class="list-group-item list-group-item-action" href="#list-item-4">Item 4</a>
                </div>
              </div> {% endcomment %}
              <div class="sidebar">
              {% if request.user.is_admin %}
                <a href="{% url 'account:manage_users' request.user.workplace_id.name %}">Manage Users</a>
                {% endif %}
                <a href="#news">All Tasks</a>
                <a href="{% url 'projects:index' request.user.workplace_id.name %}">Project</a>
                <a href="{% url 'account:user-detail' request.user.slug request.user.workplace_id %}">Settings</a>
              </div>
              {% comment %} <div class="col-10"> {% endcomment %}
              {% comment %} <div class="content"> {% endcomment %}
                <div class="container">
                {% block index_content %}
                {% endblock index_content %}
                </div>
              {% comment %} </div> {% endcomment %}
              {% comment %} </div> {% endcomment %}
     </div>
{% else %}
  <h3>Please activate your account with the link sent to your email!</h3>
{% endif %}

  <!--Main layout-->


{% endblock %}

templates/project/manage_users.html
{% extends "project/index.html" %}

{% block index_content %}
  <!--Main layout-->
{% if users_count > 1 %}
  <p>we have users</p>
{% else %}
  <p>We dont have</p>
{% endif %}
<h5>Manage Users</h5>
{% comment %} <div class="container">
    <div class="row">
        <div class="col-md-12 mb-4 text-center wow fadeIn"> {% endcomment %}
        <a href="{% url 'account:invite-users' request.user.workplace_id %}" type="button" class="btn btn-secondary float-left">Add Users</a>
            <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Users</th>
        <th scope="col">Role</th>
         {% comment %}
        <th scope="col">Heading</th>
        <th scope="col">Heading</th>
        <th scope="col">Heading</th>
        <th scope="col">Heading</th>
        <th scope="col">Heading</th>
        <th scope="col">Heading</th>
        <th scope="col">Heading</th> {% endcomment %}
      </tr>
    </thead>
    <tbody>
    {% for user in users %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'account:user-detail' user.slug user.workplace_id %}">{{ user.full_name }}</a></td>
        {% if user.role == 'US' %}
        <td>user</td>
        {% elif user.role == 'PR' %}
        <td>project manager</td>
        {% elif request.user.is_admin %}
        <td>Administrator</td>
        {% elif user.role == 'QA' %}
        <td>Quality analyst</td>
        {% endif %}
         {% comment %}
        <td>Cell</td>
        <td>Cell</td>
        <td>Cell</td>
        <td>Cell</td>
        <td>Cell</td>
        <td>Cell</td>
        <td>Cell</td> {% endcomment %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
        {% comment %} </div>
    </div>
</div> {% endcomment %}


{% endblock %}

templates/project/project_detail.html
{% extends "project/index.html" %}

{% block index_content %}
  <!--Main layout-->

<h2 class="text-center">Projects</h2>
{% comment %} <div class="container">
    <div class="row">
        <div class="col-md-12 mb-4 text-center wow fadeIn"> {% endcomment %}
          
        {% comment %} </div>
    </div>
</div> {% endcomment %}
  <div class="row">
    <h2>Project Detail</h2>
    {% comment %} <a href="#" class="feedback-form-btn btn btn-success btn-lg" id="OpenForm">Feedback</a> {% endcomment %}
    
  </div>
 
 <div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <form method="POST">
    {% csrf_token %}
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <h4 class="modal-title w-100 font-weight-bold">Create Task</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body mx-3">
        <div class="md-form mb-5">
          <i class="fas fa-user prefix grey-text"></i>
          <input type="text" id="task-name" name="task" class="form-control validate">
          <label data-error="wrong" data-success="right" for="task-name">Task name</label>
        </div>

      </div>
      <div class="modal-footer d-flex justify-content-center">
        <button type="submit" class="btn btn-deep-orange">Submit</button>
      </div>
    </div>
  </div>
  </form>
</div>

<div class="text-center">
  <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalRegisterForm">Create a Task</a>
</div>

<div class="row mt-5">
  {% comment %} <div class="col-12"> {% endcomment %}
    <div class="table-responsive">
      <table class="table">
        <thead class="black white-text">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Assigned</th>
            <th scope="col">In progress</th>
            <th scope="col">Completed</th>
            <th scope="col">Testing</th>
            <th scope="col">Review</th>
            <th scope="col">Approved</th>
            <th scope="col">Released</th>
            {% comment %} <th scope="col">Heading</th>
            <th scope="col">Heading</th> {% endcomment %}
          </tr>
        </thead>
        <tbody>
        {% if tasks %}
          
             {% for task in projects %}
            <tr>
             <th scope="row">1</th>
              <td>
                  {% for assigned in task.assigned %}
                    <div style="width: 200px;" class="card badge badge-primary text-wrap mt-2 mb-2">
                      <div class="card-body">
                        <h5 class="card-title">
                        <a href="{% url 'projects:task-detail' request.user.workplace_id task.slug assigned.pk assigned.name %}">
                        {{ assigned.name }}
                        </a>
                        </h5>
                        {% comment %} <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p> {% endcomment %}
                        <a class="card-link">{{ assigned.user_id.full_name }}</a>
                        <a class="card-link">delete</a>
                      </div>
                    </div></br>
                    {% endfor %}
              </td>
              <td>
                  {% for prog in task.progress %}
                    <div style="width: 200px;" class="card badge badge-primary text-wrap mt-2 mb-2">
                      <div class="card-body">
                        <h5 class="card-title">
                          <a href="{% url 'projects:task-detail' request.user.workplace_id task.slug prog.pk prog.name %}">
                          {{ prog.name }}
                          </a>
                        </h5>
                        {% comment %} <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p> {% endcomment %}
                        <a class="card-link">{{ prog.user_id.full_name }}</a>
                        <a class="card-link">delete</a>
                      </div>
                    </div></br>
                    {% endfor %}
              </td>

              <td>
                  {% for comp in task.completed %}
                    <div style="width: 200px;" class="card badge badge-primary text-wrap mt-2 mb-2">
                      <div class="card-body">
                        <h5 class="card-title">
                          <a href="{% url 'projects:task-detail' request.user.workplace_id task.slug comp.pk comp.name %}">
                            {{ comp.name }}
                          </a>
                        </h5>
                        {% comment %} <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p> {% endcomment %}
                        <a class="card-link">{{ comp.user_id.full_name }}</a>
                        <a class="card-link">delete</a>
                      </div>
                    </div></br>
                    {% endfor %}
              </td>

               <td>
                  {% for test in task.testing %}
                    <div style="width: 200px;" class="card badge badge-primary text-wrap mt-2 mb-2">
                      <div class="card-body">
                        <h5 class="card-title">
                          <a href="{% url 'projects:task-detail' request.user.workplace_id task.slug test.pk test.name %}">
                            {{ test.name }}
                          </a>
                        </h5>
                        {% comment %} <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p> {% endcomment %}
                        <a class="card-link">{{ test.user_id.full_name }}</a>
                        <a class="card-link">delete</a>
                      </div>
                    </div></br>
                    {% endfor %}
              </td>

              <td>
                  {% for rev in task.review %}
                    <div style="width: 200px;" class="card badge badge-primary text-wrap mt-2 mb-2">
                      <div class="card-body">
                        <h5 class="card-title">
                          <a href="{% url 'projects:task-detail' request.user.workplace_id task.slug rev.pk rev.name %}">
                            {{ rev.name }}
                          </a>
                        </h5>
                        {% comment %} <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p> {% endcomment %}
                        <a class="card-link">{{ rev.user_id.full_name }}</a>
                        <a class="card-link">delete</a>
                      </div>
                    </div></br>
                    {% endfor %}
              </td>

               <td>
                  {% for appr in task.approved %}
                    <div style="width: 200px;" class="card badge badge-primary text-wrap mt-2 mb-2">
                      <div class="card-body">
                        <h5 class="card-title">
                          <a href="{% url 'projects:task-detail' request.user.workplace_id task.slug appr.pk appr.name %}">
                            {{ appr.name }}
                          </a>
                        </h5>
                        {% comment %} <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p> {% endcomment %}
                        <a class="card-link">{{ appr.user_id.full_name }}</a>
                        <a class="card-link">delete</a>
                      </div>
                    </div></br>
                    {% endfor %}
              </td>

               <td>
                  {% for rel in task.released %}
                    <div style="width: 200px;" class="card badge badge-primary text-wrap mt-2 mb-2">
                      <div class="card-body">
                        <h5 class="card-title">
                          <a href="{% url 'projects:task-detail' request.user.workplace_id task.slug rel.pk rel.name %}">
                            {{ rel.name }}
                          </a>
                        </h5>
                        {% comment %} <p class="card-text">Some quick example text to build on the panel title and make up the bulk of the panel's content.</p> {% endcomment %}
                        <a class="card-link">{{ rel.user_id.full_name }}</a>
                        <a class="card-link">delete</a>
                      </div>
                    </div></br>
                    {% endfor %}
              </td>
            </tr>
          {% endfor %}
        {% else %}
        <h2>NO taks for this project yet, please create one!</h2>
        {% endif %}
        </tbody>
      </table>
    </div>
  {% comment %} </div> {% endcomment %}
  
</div>

<script type="text/javascript">
   $(document).ready(function(){
        $("#OpenForm").click(function(){
            $(".feedback_form_area").animate({
                width: "toggle"
            });
        });
    });
</script>
{% endblock %}

templates/project/project_index.html
{% extends "project/index.html" %}

{% block index_content %}
  <!--Main layout-->

<h2 class="text-center">Projects</h2>
{% comment %} <div class="container">
    <div class="row">
        <div class="col-md-12 mb-4 text-center wow fadeIn"> {% endcomment %}
          
        {% comment %} </div>
    </div>
</div> {% endcomment %}
  <div class="row">
    {% comment %} <div class="col">
      
    </div> {% endcomment %}
    {% if request.user.is_admin %}
    <div class="col">
      <div class="text-center" id="create" style="width: 200px; height: 30px; margin: 0px 20px; background-color: #007E33;">
          <span class="text-center" style="color:white;">Create a Project</span>
      </div><br>
      <form id="project_form" method="POST"> 
      {% csrf_token %}
        <div>
          <input type="text" name="project_name" placeholder="Name of project"/>
        </div><br>
          <div>
            <span>Project Manager</span>
            <select name="project_manager">
              {% for user in users %}
                <option value='{{ user.id }}'>{{ user.full_name }}</option>
              
              {% endfor %}
                <option value='{{ request.user.id }}'>{{ request.user.full_name }}</option>
            </select>
          </div> <br>
        <button class="btn btn-primary" id="submit" type="submit">create project</button>
      </form>
    </div>
     {% endif %}
  </div>
 

<div class="row mt-5">
  <div class="col-12">
  {% if projects %}
   <h3>List of Projects</h3>
  {% for project in projects %}
    
   
    {% comment %} <div class="d-flex flex-column"> {% endcomment %}
      <div class="p-2 mb-2 w-100">
        <p class="note note-primary">
         <a href="{{ project.get_absolute_url }}">{{ project.name }}</a><br>
          <small>{{ project.project_manager.full_name }}</small>
        </p>
        
      </div>
      {% comment %} <div class="p-2">Flex item 2</div>
      <div class="p-2">Flex item 3</div> {% endcomment %}
    {% comment %} </div> {% endcomment %}
    
    
  {% endfor %}
  {% else %}
     {% if request.user.is_admin %}
      <h3>You do not have any project yet, create projects above</h3>
      {% else %}
      <h3>You do not have any project yet, contact your administator to create one!</h3>
     {% endif %}
  {% endif %}
  </div>
  
</div>

<script type="text/javascript">
  var project = document.getElementById("project_form");
  const sub = document.querySelector('#submit');
  const btn = document.querySelector('#create');

  {% comment %} const rbs = document.querySelectorAll('input[name="form-check-input"]'); {% endcomment %}
    {% comment %} if(btn.checked) {
        divworkplace.style.display = "block";  
    }  {% endcomment %}
    project.style.display = "none";

    btn.addEventListener("click", function(){
        project.style.display = "block";
        console.log("project");
    });
    sub.addEventListener("click", function(){
        project.style.display = "none";
        console.log("project");
    });


</script>
{% endblock %}

templates/project/single_user_index.html
{% extends "base.html" %}

{% block content %}
  <!--Main layout-->
  
    <div class="container">

    <div class="row mx-auto">
        <div class="col-md-12 mb-4 text-center wow fadeIn">
          <h3 class="display-3 font-weight-bold mb-0 pt-md-5 pt-5">Single User Index page</h3>
          
      </div>

    </div>

  <!--Main layout-->


{% endblock %}

templates/project/welcome.html
{% extends "project/index.html" %}

{% block index_content %}
  <!--Main layout-->
{% comment %} {% if users_count > 1 %}
  <p>we have users</p>
{% else %}
  <p>We dont have</p>
{% endif %} {% endcomment %}
<div class="container">
<div class="row">
<div class="col-md-12 mb-4 text-center wow fadeIn">
<div class="d-flex flex-row justify-content-center">
  <div class="p-2">
    <!-- Card -->
    <div class="card w-75 mh-25">

      <!-- Card image -->
      <div class="view overlay">
        <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/men.jpg"
          alt="Card image cap">
        <a href="{% url 'account:manage_users' workplace %}">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

      <!-- Card content -->
      <div class="card-body">

        <!-- Title -->
        <h4 class="card-title">Manage Users</h4>
        <!-- Text -->
        <p class="card-text">You can invite users to your workplace and manage them.</p>
        <!-- Button -->
        <a href="{% url 'account:manage_users' workplace %}" class="btn btn-primary">Users</a>

      </div>

    </div>
    <!-- Card -->
   
  </div>
  <div class="p-2">
    <!-- Card -->
    <div class="card w-75 mh-25">

      <!-- Card image -->
      <div class="view overlay">
        <img class="card-img-top" src="https://mdbootstrap.com/img/Mockups/Lightbox/Thumbnail/img%20(67).jpg"
          alt="Card image cap">
        <a href="{% url 'projects:index' workplace %}">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

      <!-- Card content -->
      <div class="card-body">

        <!-- Title -->
        <h4 class="card-title">Create a Project</h4>
        <!-- Text -->
        <p class="card-text">Create a projects and create tasks under them to organize your tasks more efficiently.</p>
        <!-- Button -->
        <a href="{% url 'projects:index' workplace %}" class="btn btn-primary">Button</a>

      </div>

    </div>
    <!-- Card -->
  </div>
  <div class="p-2">
    <!-- Card -->
    <div class="card w-75 mh-25">

      <!-- Card image -->
      <div class="view overlay">
        <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/men.jpg"
          alt="Card image cap">
        <a href="#!">
          <div class="mask rgba-white-slight"></div>
        </a>
      </div>

      <!-- Card content -->
      <div class="card-body">

        <!-- Title -->
        <h4 class="card-title">All Tasks</h4>
        <!-- Text -->
        <p class="card-text">You can create tasks here and view all tasks irrespective of their projects.</p>
        <!-- Button -->
        <a href="#" class="btn btn-primary">Button</a>

      </div>

    </div>
    <!-- Card -->
  </div>
</div>
</div>
</div>
</div>


{% endblock %}